### ISSUE TITLE
mispelling

### ISSUE THREAD

**Issue by leclercfl** [rglez/nuclear#5] opened 2023-09-27 16:53 UTC
conda create -n nuclear
source activate nuclear
pip install -r requirements.txt nuklear --> nuclear

**Comment by rglez** [comment] 2023-09-27 17:36
Well, this is not a typo.

The problem is that "nuclear" was already taken in PyPI, so it would be
impossible to have another project with the same name.

I chose nuklear to maintain the phonetic but we could decide to explicitly
mention this in the README. It is the only place where the "k" comes up.

As it can be seen in the tab "Actions" in Github, a Continuous Integration
(CI) workflow has been set up and tests are  passing so far. Those tests
include the installation of nuklear.

Feel free to close this issue ;)

**Comment by leclercfl** [comment] 2023-09-28 10:25
OK, ya entendí. 
I could install properly now (with the nuclear script in the bin directory of the virtual environment) and I have a working develop version. Nice !

**Comment by leclercfl** [comment] 2023-09-28 10:26
Fixed issue then.

**Closed as completed** 2023-09-28 10:25 UTC
Labels: documentation
